### ISSUE TITLE
unnecessary file

### ISSUE THREAD

**Issue by Cavalon-io** [Maikxx/web-app-from-scratch-18-19#8]
This file could be moved into the package.json. Not really need a seperate file for just one line.

https://github.com/Maikxx/web-app-from-scratch-18-19/blob/fe31f397b2d1055eaf9b725c1b54d0ced29fa985/.postcssrc#L1

**Comment by Maikxx** [comment]
Definitely don't agree with this

**Comment by Cavalon-io** [comment]
Than not hé.
